# Generated by Django 4.1 on 2022-09-02 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="제목")),
                ("content", models.TextField(max_length=2000, verbose_name="내용")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="게시글 등록 일자"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PostType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "post_type",
                    models.CharField(
                        choices=[
                            ("Notice", "공지사항"),
                            ("Admin", "운영게시판"),
                            ("General", "자유게시판"),
                        ],
                        default="General",
                        max_length=10,
                        verbose_name="게시판 타입",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PostUpdatedLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="게시글 업데이트 일자"),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="posts.post",
                        verbose_name="게시글",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="수정자",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="post_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="posts.posttype",
                verbose_name="게시판 타입",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="작성자",
            ),
        ),
    ]
