version: '3.9'
services:
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/django/static
    ports:
      - 80:80
    depends_on:
      - app
  app:
    build: .
    volumes:
      - .:/django
      - static_volume:/django/static
    image: app:django
    container_name: django_container
    env_file:
      - ./.env.prod
    command: sh -c "python manage.py collectstatic --no-input && python manage.py migrate && gunicorn Wayne_Hills.wsgi:application --bind 0.0.0.0:8000"

volumes:
  static_volume:
