# Generated by Django 4.0.6 on 2022-08-31 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=12, unique=True, verbose_name='사용자 아이디')),
                ('password', models.CharField(max_length=128, verbose_name='비밀번호')),
                ('gender', models.CharField(choices=[('male', '남성'), ('female', '여성')], max_length=20, verbose_name='성별')),
                ('age', models.IntegerField(verbose_name='나이')),
                ('joined_date', models.DateTimeField(auto_now_add=True, verbose_name='가입일')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('manager', '운영자'), ('general', '일반 사용자')], max_length=100, verbose_name='유저 유형')),
            ],
        ),
    ]
